# Generated by Django 5.2 on 2025-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habiro_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
