# Generated by Django 5.2 on 2025-04-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habiro_dashboard', '0003_habit_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='habit',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
