# Generated by Django 5.2 on 2025-05-08 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_remove_adminuser_groups_remove_adminuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only Gmail addresses are allowed (e.g., example@gmail.com)', regex='^[\\w\\.-]+@gmail\\.com$')]),
        ),
    ]
