# Generated by Django 5.1.6 on 2025-06-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_responses', '0002_cointransaction_usercoins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoins',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
        migrations.DeleteModel(
            name='UserCoins',
        ),
    ]
