# Generated by Django 5.1.6 on 2025-05-02 07:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Verification', 'verbose_name_plural': 'OTP Verifications'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=255, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='password',
            field=models.CharField(default='default_password', editable=False, max_length=128, verbose_name='password hash'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='one time password'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['email', 'otp'], name='app_fronten_email_4e2823_idx'),
        ),
    ]
