# Generated by Django 5.2.1 on 2025-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0002_customuser_phone_number_otpverification_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='password',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
