# Generated by Django 5.2 on 2025-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0003_alter_otpverification_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
