# Generated by Django 5.2.4 on 2025-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0004_challenge_challengehabit_userchallenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
