# Generated by Django 5.2 on 2025-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0002_customuser_active_time'),
        ('app_frontend', '0004_challenge_challengehabit_userchallenge_and_more'),
    ]

    operations = [
    ]
