# Generated by Django 5.2.4 on 2025-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengehabit',
            name='daily_status',
            field=models.JSONField(default=dict),
        ),
    ]
