# Generated by Django 5.2 on 2025-07-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_frontend', '0005_merge_20250725_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_time',
        ),
    ]
