# Generated by Django 5.2 on 2025-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('best_time', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Game Statistics',
            },
        ),
    ]
