# Generated by Django 5.2 on 2025-05-11 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('coins', models.IntegerField(default=100)),
                ('gems', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('daily_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('last_claim_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
