# Generated by Django 5.2.4 on 2025-07-26 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_reward_gems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='streak_cycle_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to=settings.AUTH_USER_MODEL),
        ),
    ]
