# Generated by Django 5.2 on 2025-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_reward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='consecutive_claims',
            field=models.IntegerField(default=0),
        ),
    ]
