# Generated by Django 5.2 on 2025-07-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_reward_consecutive_claims'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='consecutive_claims',
        ),
    ]
