# Generated by Django 5.2 on 2025-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_remove_reward_consecutive_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='streak_cycle_day',
            field=models.IntegerField(default=0),
        ),
    ]
