# Generated by Django 5.2 on 2025-05-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_email_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
