# Generated by Django 5.2 on 2025-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Personal Development', 'Personal Development'), ('Productivity', 'Productivity'), ('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Mental Well-Being', 'Mental Well-Being')], max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
            ],
        ),
    ]
