# Generated by Django 5.2 on 2025-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='achievements/')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlock_condition', models.CharField(blank=True, max_length=50)),
                ('is_collected', models.BooleanField(default=False)),
            ],
        ),
    ]
