# Generated by Django 5.2 on 2025-05-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='unlocked',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user_id',
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('unlocked', models.BooleanField(default=False)),
                ('is_collected', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
        ),
    ]
