# Generated by Django 5.2 on 2025-07-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileandchat', '0002_message_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
