// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFXa0V2nrgcN8kN2O34JxjZ_BCcnCYtRY',
    appId: '1:561054008386:web:1208d438984682a0db19db',
    messagingSenderId: '561054008386',
    projectId: 'habitro-34',
    authDomain: 'habitro-34.firebaseapp.com',
    storageBucket: 'habitro-34.firebasestorage.app',
    measurementId: 'G-BFCRTS3MPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdlLfEFRaSRqjZWIr0sdS7-u1OxyidQ6E',
    appId: '1:561054008386:android:f3c98f10aed23138db19db',
    messagingSenderId: '561054008386',
    projectId: 'habitro-34',
    storageBucket: 'habitro-34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzbtVU-I-DRvG9a6trjGK4z9jQCi75--E',
    appId: '1:561054008386:ios:218e47a6cb96be8ddb19db',
    messagingSenderId: '561054008386',
    projectId: 'habitro-34',
    storageBucket: 'habitro-34.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzbtVU-I-DRvG9a6trjGK4z9jQCi75--E',
    appId: '1:561054008386:ios:218e47a6cb96be8ddb19db',
    messagingSenderId: '561054008386',
    projectId: 'habitro-34',
    storageBucket: 'habitro-34.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFXa0V2nrgcN8kN2O34JxjZ_BCcnCYtRY',
    appId: '1:561054008386:web:3f55e3144d44bdb2db19db',
    messagingSenderId: '561054008386',
    projectId: 'habitro-34',
    authDomain: 'habitro-34.firebaseapp.com',
    storageBucket: 'habitro-34.firebasestorage.app',
    measurementId: 'G-NY61B6NPZJ',
  );
}
